// Shared expiry records live on each client; no separate customer data copy.
function expiryToday(){return new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Dubai'});}
function expiryDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))return null;const d=new Date(s+'T00:00:00Z');return !isNaN(d)&&d.toISOString().slice(0,10)===s?d:null;}
function expiryReminder(s){const d=expiryDate(s);if(!d)return '';const m=new Date(d);m.setUTCDate(1);m.setUTCMonth(m.getUTCMonth()-2);const last=new Date(Date.UTC(m.getUTCFullYear(),m.getUTCMonth()+1,0)).getUTCDate();m.setUTCDate(Math.min(d.getUTCDate(),last));const sixty=new Date(d.getTime()-60*86400000);return new Date(Math.min(m,sixty)).toISOString().slice(0,10);}
function expiryRecords(){const rows=[];clients.forEach(c=>{if(!hasSectionAccess('clients'))return;if(c.licenceExpiry&&expiryDate(c.licenceExpiry))rows.push({client:c,key:'licence',name:'Trade licence',date:c.licenceExpiry,follow:c.licenceFollowup?.date===c.licenceExpiry?c.licenceFollowup:{}});Object.entries(c.expiryDocuments||{}).forEach(([key,d])=>{if(d&&expiryDate(d.date))rows.push({client:c,key,name:d.name||'Document',date:d.date,follow:d});});});return rows.sort((a,b)=>a.date.localeCompare(b.date)||a.client.name.localeCompare(b.client.name));}
function expiryRows(rows){return rows.map(r=>{const overdue=r.date<expiryToday(),due=expiryToday()>=expiryReminder(r.date),editable=canChangeSection('clients')&&canEdit(r.client.advisorId);return '<div class="expiry-row"><div><b>'+uiText(r.client.name)+'</b><small>'+uiText(r.name)+' · '+fD(r.date)+'</small><span class="badge '+(overdue?'bover':due?'bpending':'bactive')+'">'+(overdue?'Expired':due?'Renewal due soon':'Upcoming')+'</span><small>Reminder starts '+fD(expiryReminder(r.date))+'</small></div><div class="expiry-follow"><label><input type="checkbox" '+(r.follow.clientNotifiedAt?'checked ':'')+(!editable?'disabled ':'')+'data-client="'+uiText(r.client.id)+'" data-key="'+uiText(r.key)+'" onchange="setExpiryFollowup(this,\'clientNotifiedAt\')"> Client informed</label><label><input type="checkbox" '+(r.follow.ftaUpdatedAt?'checked ':'')+(!editable?'disabled ':'')+'data-client="'+uiText(r.client.id)+'" data-key="'+uiText(r.key)+'" onchange="setExpiryFollowup(this,\'ftaUpdatedAt\')"> FTA updated / not required</label><button class="btn btn-g" data-client="'+uiText(r.client.id)+'" onclick="openExpiryEditor(this.dataset.client)">'+(editable?'Edit expiry dates':'View dates')+'</button></div></div>';}).join('');}
function expiryPanel(rows,title){return '<div class="expiry-panel"><h3>'+uiText(title)+'</h3><p>Reminders start at least two months before expiry. Inform the client, collect renewed documents and update the FTA portal where applicable. Checkboxes record your manual follow-up.</p>'+expiryRows(rows)+'</div>';}
const expiryBannerBase=renderBanner;
renderBanner=function(){expiryBannerBase();const wrap=document.getElementById('deadline-banner-wrap');if(!wrap||!CU)return;const rows=expiryRecords().filter(r=>expiryReminder(r.date)<=expiryToday());const tax=wrap.firstElementChild;/* Replace inherited 60-day licence alerts with one combined tracker. */wrap.innerHTML=entries.some(e=>{const d=dLRecur(e);return d!==null&&d>=0&&d<=7;})&&tax?tax.outerHTML:'';if(rows.length)wrap.innerHTML+='<details class="expiry-alert"><summary>'+rows.length+' license / document '+(rows.length===1?'expiry needs':'expiries need')+' attention</summary>'+expiryPanel(rows,'Renewals & FTA follow-up')+'</details>';};
function renderExpiryCalendar(){const target=document.getElementById('calendar-expiries');if(!target)return;const search=(document.getElementById('expiry-search')?.value||'').toLowerCase();const scope=document.getElementById('expiry-scope')?.value||'attention';const rows=expiryRecords().filter(r=>(scope==='all'||expiryReminder(r.date)<=expiryToday())&&(!search||(r.client.name+' '+r.name).toLowerCase().includes(search)));target.innerHTML=rows.length?expiryPanel(rows,scope==='all'?'All tracked expiry dates':'Expiries requiring attention'):'<p class="expiry-empty">No matching expiry dates. Open a client and choose License & document expiry to add dates.</p>';}
const expiryCalendarBase=renderCalendar;renderCalendar=function(){expiryCalendarBase();renderExpiryCalendar();};
const expiryDetailBase=openClientDetail;openClientDetail=function(cid){expiryDetailBase(cid);const c=clients.find(x=>x.id===cid),target=document.getElementById('client-detail-content');if(!c||!target||!hasSectionAccess('clients'))return;target.innerHTML+='<div class="expiry-client-tools"><button class="btn btn-p" data-client="'+uiText(cid)+'" onclick="openExpiryEditor(this.dataset.client)">License & document expiry</button></div>'+expiryPanel(expiryRecords().filter(r=>r.client.id===cid),'Expiry dates & follow-up');};
let expiryClientId=null;
function openExpiryEditor(cid){if(!hasSectionAccess('clients'))return;const c=clients.find(x=>x.id===cid);if(!c)return;expiryClientId=cid;const editable=canChangeSection('clients')&&canEdit(c.advisorId);document.getElementById('expiry-client-name').textContent=c.name;document.getElementById('expiry-license-date').value=c.licenceExpiry||'';document.getElementById('expiry-license-date').disabled=!editable;const defaults=['Emirates ID (Owner)','Passport (Owner)','Residence visa','Establishment card','Other license / permit'];const docs={...c.expiryDocuments};defaults.forEach((name,i)=>{const key='default_'+i;if(!docs[key])docs[key]={name,date:''};});document.getElementById('expiry-document-fields').innerHTML=Object.entries(docs).map(([key,d])=>'<label class="expiry-field">'+uiText(d.name)+'<input type="date" data-expiry-key="'+uiText(key)+'" data-expiry-name="'+uiText(d.name)+'" value="'+uiText(d.date||'')+'" '+(!editable?'disabled':'')+'></label>').join('');document.getElementById('expiry-save').hidden=!editable;document.getElementById('expiry-add').hidden=!editable;document.getElementById('ov-expiry').classList.add('open');}
function addExpiryDocument(){if(!canChangeSection('clients'))return;const name=document.getElementById('expiry-custom-name').value.trim();if(!name){toast('Enter a document name','err');return;}const key='custom_'+crypto.randomUUID();const label=document.createElement('label');label.className='expiry-field';label.textContent=name;const input=document.createElement('input');input.type='date';input.dataset.expiryKey=key;input.dataset.expiryName=name;label.appendChild(input);document.getElementById('expiry-document-fields').appendChild(label);document.getElementById('expiry-custom-name').value='';input.focus();}
async function saveExpiryDates(){const c=clients.find(x=>x.id===expiryClientId);if(!c||!canChangeSection('clients')||!canEdit(c.advisorId))return;const licence=document.getElementById('expiry-license-date').value;const inputs=[...document.querySelectorAll('#expiry-document-fields input')];if((licence&&!expiryDate(licence))||inputs.some(i=>i.value&&!expiryDate(i.value))){toast('Enter valid expiry dates','err');return;}const docs={};inputs.forEach(i=>{if(i.value){const old=c.expiryDocuments?.[i.dataset.expiryKey];docs[i.dataset.expiryKey]={name:i.dataset.expiryName,date:i.value,...(old?.date===i.value?{clientNotifiedAt:old.clientNotifiedAt||null,ftaUpdatedAt:old.ftaUpdatedAt||null}:{})};}});const updates={licenceExpiry:licence||null,expiryDocuments:Object.keys(docs).length?docs:null};if(licence!==c.licenceExpiry)updates.licenceFollowup=null;try{await db.ref('clients/'+c.id).update(updates);Object.assign(c,updates);closeM('expiry');renderAll();openClientDetail(c.id);toast('Expiry dates saved','ok');}catch(e){toast('Could not save expiry dates. Please retry.','err');}}
async function setExpiryFollowup(input,field){const c=clients.find(x=>x.id===input.dataset.client),key=input.dataset.key;if(!c||!canChangeSection('clients')||!canEdit(c.advisorId)||!['clientNotifiedAt','ftaUpdatedAt'].includes(field))return;const r=expiryRecords().find(r=>r.client.id===c.id&&r.key===key);if(!r)return;input.disabled=true;const value=input.checked?new Date().toISOString():null;try{const path=key==='licence'?'licenceFollowup':'expiryDocuments/'+key;await db.ref('clients/'+c.id+'/'+path).update({date:r.date,[field]:value});if(key==='licence')c.licenceFollowup={...r.follow,date:r.date,[field]:value};else c.expiryDocuments[key][field]=value;renderBanner();renderExpiryCalendar();toast('Follow-up saved','ok');}catch(e){input.checked=!input.checked;toast('Could not save follow-up. Please retry.','err');}finally{input.disabled=false;}}
// Refresh reminders across midnight even when the portal stays open.
setInterval(()=>{if(CU){renderBanner();renderExpiryCalendar();}},60000);
