// Staff metrics use recorded dates, not updatedAt estimates.
function performanceDay(s){if(!s)return '';if(/^\d{4}-\d{2}-\d{2}$/.test(s))return expiryDate(s)?s:'';const d=new Date(s);return isNaN(d)?'':d.toLocaleDateString('en-CA',{timeZone:'Asia/Dubai'});}
function performanceRange(preset){const today=expiryToday(),d=expiryDate(today),year=d.getUTCFullYear(),month=d.getUTCMonth();let start='';if(preset==='month')start=new Date(Date.UTC(year,month,1)).toISOString().slice(0,10);if(preset==='quarter')start=new Date(Date.UTC(year,Math.floor(month/3)*3,1)).toISOString().slice(0,10);if(preset==='year')start=year+'-01-01';return {start,end:today};}
function setPerformancePeriod(){const preset=document.getElementById('perf-period').value;if(preset!=='custom'){const r=performanceRange(preset);document.getElementById('perf-start').value=r.start;document.getElementById('perf-end').value=r.end;}renderWorkload();}
function performanceInRange(date,start,end){const day=performanceDay(date);return !!day&&(!start||day>=start)&&(!end||day<=end);}
function performanceStaff(){const all=new Map(advisors.map(a=>[a.id,{id:a.id,name:a.name,role:a.role||'Advisor'}]));Object.entries(users).forEach(([id,u])=>{if(u?.name&&!all.has(id))all.set(id,{id,name:u.name,role:u.role||'Staff'});});const ids=new Set([...entries,...acctEntries,...tasksData,...Object.values(feesData)].map(r=>r?.advisorId).filter(Boolean));ids.forEach(id=>{if(!all.has(id))all.set(id,{id,name:id==='office'?'Office staff':id,role:'Assigned staff'});});return [...all.values()].filter(a=>isM()||isSupervisor()||a.id===myAId()).sort((a,b)=>a.name.localeCompare(b.name));}
function staffMetrics(a,start,end,currency){
 const tax=entries.filter(e=>e.advisorId===a.id&&expiryDate(e.deadline)),accounts=acctEntries.filter(e=>e.advisorId===a.id),tasks=tasksData.filter(e=>e.advisorId===a.id&&e.status!=='cancelled');
 const openAccounts=accounts.filter(e=>e.status!=='done'),openTasks=tasks.filter(e=>e.status!=='completed');
 const completedAccounts=acctEntries.filter(e=>e.status==='done'&&(e.performance?.completionAdvisorId||e.advisorId)===a.id&&performanceInRange(e.performance?.completedAt,start,end));
 const completedTasks=tasksData.filter(e=>e.status==='completed'&&(e.performance?.completionAdvisorId||e.advisorId)===a.id&&performanceInRange(e.performance?.completedAt,start,end));
 const invoices=Object.entries(feesData).map(([id,i])=>({...i,id})).filter(i=>i.service&&i.advisorId===a.id&&(i.currency||i.igCurrency||'AED')===currency&&i.status!=='void'&&performanceInRange(i.date,start,end));
 const billedInvoices=invoices.filter(i=>['sent','paid','overdue'].includes(i.status));
 const sum=list=>list.reduce((n,i)=>n+(Number(i.amount)||0),0);
 const filed=entries.flatMap(e=>Object.values(e.performance?.filings||{}).filter(x=>x.advisorId===a.id&&performanceInRange(x.filedAt,start,end)).map(x=>({...x,clientId:e.clientId,type:e.type})));
 const reviewed=completedAccounts.filter(e=>e.performance?.reviewedAt&&e.performance?.reviewSubmissions>0),firstPass=reviewed.filter(e=>!(e.performance?.reworkCount>0));
 const timed=completedTasks.filter(e=>expiryDate(e.performance?.completionDue)),onTime=timed.filter(e=>performanceDay(e.performance.completedAt)<=e.performance.completionDue);
 return {filed,staff:a,tax,accounts,tasks,openAccounts,openTasks,load:tax.length+openAccounts.length+openTasks.length,clients:clients.filter(c=>c.advisorId===a.id&&(c.status||'active')==='active').length,overdueTax:tax.filter(e=>stOf(e)==='overdue').length,soonTax:tax.filter(e=>{const n=dLRecur(e);return n!==null&&n>=0&&n<=14;}).length,overdueTasks:openTasks.filter(e=>e.due&&e.due<expiryToday()).length,blocked:openAccounts.filter(e=>e.status==='pendingdocs').length+openTasks.filter(e=>e.status==='docspending').length,waitingReview:openAccounts.filter(e=>e.status==='review').length,completedAccounts,completedTasks,reviewed,firstPass,timed,onTime,invoices,billedInvoices,billed:sum(billedInvoices),paid:sum(billedInvoices.filter(i=>i.status==='paid')),outstanding:sum(billedInvoices.filter(i=>i.status!=='paid')),draft:sum(invoices.filter(i=>!['sent','paid','overdue'].includes(i.status))),undatedDone:accounts.filter(e=>e.status==='done'&&!e.performance?.completedAt).length+tasks.filter(e=>e.status==='completed'&&!e.performance?.completedAt).length};
}
function performanceFilters(){return {start:document.getElementById('perf-start')?.value||'',end:document.getElementById('perf-end')?.value||'',currency:document.getElementById('perf-currency')?.value||'AED',staff:document.getElementById('perf-staff')?.value||'all',search:(document.getElementById('perf-search')?.value||'').trim().toLowerCase(),sort:document.getElementById('perf-sort')?.value||'load'};}
function performanceRows(){const f=performanceFilters();return performanceStaff().filter(a=>(f.staff==='all'||a.id===f.staff)&&(!f.search||(a.name+' '+a.role).toLowerCase().includes(f.search))).map(a=>staffMetrics(a,f.start,f.end,f.currency)).sort((a,b)=>f.sort==='name'?a.staff.name.localeCompare(b.staff.name):f.sort==='billed'&&isM()&&hasSectionAccess('fees')?b.billed-a.billed:f.sort==='done'?(b.filed.length+b.completedAccounts.length+b.completedTasks.length)-(a.filed.length+a.completedAccounts.length+a.completedTasks.length):b.load-a.load);}
let performanceTab='workload';
function setPerformanceTab(tab){performanceTab=tab;renderWorkload();}
function performanceRate(n,total){return total?Math.round(n/total*100)+'% ('+n+'/'+total+')':'Not recorded';}
function performanceMoney(n){return Number(n||0).toLocaleString('en-AE',{minimumFractionDigits:2,maximumFractionDigits:2});}
renderWorkload=function(){
 if(!CU||!hasSectionAccess('workload'))return;
 const staffSelect=document.getElementById('perf-staff'),selected=staffSelect?.value||'all';if(staffSelect){staffSelect.innerHTML='<option value="all">'+(isM()?'All staff':'My performance')+'</option>'+performanceStaff().map(a=>'<option value="'+uiText(a.id)+'">'+uiText(a.name)+'</option>').join('');staffSelect.value=selected;}
 const f=performanceFilters(),error=document.getElementById('perf-error');if(f.start&&f.end&&f.start>f.end){error.textContent='Start date must be before the end date.';document.getElementById('workload-cards').innerHTML='';document.getElementById('perf-summary').innerHTML='';return;}error.textContent='';
 const rows=performanceRows(),max=Math.max(1,...rows.map(r=>r.load)),money=isM()&&hasSectionAccess('fees');
 document.getElementById('perf-export').hidden=!isM();document.getElementById('perf-currency-wrap').hidden=!money;document.getElementById('perf-sort').querySelectorAll('option[value="billed"]').forEach(o=>o.hidden=!money);
 const summary=[['Active clients',rows.reduce((n,r)=>n+r.clients,0)],['Current open work',rows.reduce((n,r)=>n+r.load,0)],['Overdue tax / tasks',rows.reduce((n,r)=>n+r.overdueTax+r.overdueTasks,0)],['Completed in period',rows.reduce((n,r)=>n+r.filed.length+r.completedAccounts.length+r.completedTasks.length,0)]];
 document.getElementById('perf-summary').innerHTML=summary.map(([label,value])=>'<div class="perf-summary-item"><small>'+label+'</small><strong>'+value+'</strong></div>').join('');
 document.getElementById('perf-workload-tab').classList.toggle('active',performanceTab==='workload');document.getElementById('perf-performance-tab').classList.toggle('active',performanceTab==='performance');
 const target=document.getElementById('workload-cards');target.className=performanceTab==='workload'?'staff-workload-grid':'staff-performance-grid';
 target.innerHTML=rows.map(r=>{const a=r.staff,action='<button class="btn btn-g" data-staff="'+uiText(a.id)+'" onclick="openStaffPerformance(this.dataset.staff)">View evidence ↗</button>',head='<div class="staff-card-head"><div><h3>'+uiText(a.name)+'</h3><small>'+uiText(a.role)+'</small></div>'+action+'</div>';
 if(performanceTab==='workload')return '<article class="staff-workload-card">'+head+'<div class="staff-load-total"><strong>'+r.load+'</strong><span>open work items</span></div><div class="staff-load-bar" aria-hidden="true"><span style="width:'+r.tax.length/max*100+'%;background:var(--blue)"></span><span style="width:'+r.openAccounts.length/max*100+'%;background:var(--green)"></span><span style="width:'+r.openTasks.length/max*100+'%;background:var(--amber)"></span></div><div class="staff-breakdown"><span>Tax entries <b>'+r.tax.length+'</b></span><span>Accounting <b>'+r.openAccounts.length+'</b></span><span>Tasks <b>'+r.openTasks.length+'</b></span></div><div class="staff-signals"><span>'+r.clients+' active clients</span><span class="'+(r.overdueTax+r.overdueTasks?'staff-risk':'')+'">'+(r.overdueTax+r.overdueTasks)+' overdue</span><span>'+r.soonTax+' tax due ≤14d</span><span>'+r.blocked+' waiting for documents</span></div></article>';
 return '<article class="staff-workload-card">'+head+'<div class="staff-performance-metrics"><div><small>Tax filings recorded</small><strong>'+r.filed.length+'</strong></div><div><small>Accounting completed</small><strong>'+r.completedAccounts.length+'</strong></div><div><small>Tasks completed</small><strong>'+r.completedTasks.length+'</strong></div><div><small>Tasks on time</small><b>'+performanceRate(r.onTime.length,r.timed.length)+'</b></div><div><small>Completed reports shared</small><b>'+performanceRate(r.completedAccounts.filter(e=>e.reportShared).length,r.completedAccounts.length)+'</b></div></div>'+(money?'<div class="staff-billing"><span>'+uiText(f.currency)+' · Invoice dates in selected period</span><div><small>Billed</small><b>'+performanceMoney(r.billed)+'</b></div><div><small>Paid on those invoices</small><b>'+performanceMoney(r.paid)+'</b></div><div><small>Still outstanding</small><b>'+performanceMoney(r.outstanding)+'</b></div><small>Drafts: '+performanceMoney(r.draft)+' · excluded from billed</small></div>':'')+'<p class="staff-data-note">'+r.undatedDone+' older completed records have no completion date and are excluded from period totals.</p></article>';
 }).join('')||'<div class="empty-state"><h3>No staff match these filters.</h3><p>Add advisors or assign work to a staff member.</p></div>';
 const unassigned=entries.filter(e=>!e.advisorId&&expiryDate(e.deadline)).length+acctEntries.filter(e=>e.status!=='done'&&!e.advisorId).length+tasksData.filter(e=>!['completed','cancelled'].includes(e.status)&&!e.advisorId).length;
 const invoiceGaps=Object.values(feesData).filter(i=>i?.service&&i.status!=='void'&&(!i.advisorId||!performanceDay(i.date))).length;
 document.getElementById('perf-coverage').textContent=isM()?unassigned+' unassigned work items'+(money?' · '+invoiceGaps+' invoices missing an advisor or invoice date':'')+'. Assign these records to include them in staff reporting.':'';
};
function openStaffPerformance(id){const a=performanceStaff().find(a=>a.id===id);if(!a||!hasSectionAccess('workload'))return;const f=performanceFilters(),r=staffMetrics(a,f.start,f.end,f.currency),money=isM()&&hasSectionAccess('fees');document.getElementById('staff-evidence-title').textContent=a.name+' · Performance evidence';
 const item=(title,date,detail)=>'<li><b>'+uiText(title)+'</b><small>'+uiText(date||'No date')+' · '+uiText(detail)+'</small></li>';
 document.getElementById('staff-evidence-body').innerHTML='<p>Period: '+uiText(f.start||'All recorded dates')+' to '+uiText(f.end||'present')+'. Current workload is a snapshot, not limited by these dates.</p><h4>Completed work ('+(r.filed.length+r.completedAccounts.length+r.completedTasks.length)+')</h4><ul class="staff-evidence-list">'+[...r.filed.map(e=>item(cliName(e.clientId)+' · '+e.type,performanceDay(e.filedAt),'Tax filing · deadline '+(e.deadline||'not set'))),...r.completedAccounts.map(e=>item(cliName(e.clientId)+' · '+e.service,performanceDay(e.performance.completedAt),'Accounting · '+(e.month||'No service month'))),...r.completedTasks.map(e=>item(e.title,performanceDay(e.performance.completedAt),'Task · '+(e.performance.completionDue?'due '+e.performance.completionDue:'no recorded due date')))].join('')+'</ul>'+(money?'<h4>Invoices credited to this staff member · '+uiText(f.currency)+'</h4><ul class="staff-evidence-list">'+r.invoices.map(i=>item((i.invoiceNo||'Invoice')+' · '+cliName(i.clientId),i.date,(i.status||'Draft')+' · '+f.currency+' '+performanceMoney(i.amount))).join('')+'</ul>':'')+'<h4>Current overdue work</h4><ul class="staff-evidence-list">'+[...r.tax.filter(e=>stOf(e)==='overdue').map(e=>item(cliName(e.clientId)+' · '+e.type,e.deadline,'Tax entry')),...r.openTasks.filter(e=>e.due&&e.due<expiryToday()).map(e=>item(e.title,e.due,'Task'))].join('')+'</ul><div class="performance-definitions"><h4>How to read these metrics</h4><p>Tax filings and completions are recorded from the tracking update onward; older filing history is not reconstructed. Completion counts use recorded completion dates and the staff assignment at completion. On-time tasks use the due date captured at completion. Advisor and reviewer names are informational; completing work requires no approval. Report sharing is tracked separately from completion.</p><p>Billing uses the invoice advisor and invoice date. Sent, overdue and paid invoices count as billed; drafts and voids do not. Paid amounts describe the current status of those invoices, not cash received during this period. Amounts are invoice totals in the selected currency, not profit or net revenue.</p><p>For promotion and salary reviews, compare several periods and discuss client complexity, quality, responsibilities and client feedback alongside these figures. Open item counts show workload volume; they do not measure effort or capacity.</p></div>';
 if(isM())document.getElementById('staff-evidence-body').innerHTML+='<div class="salary-planning"><h4>Salary planning · AED</h4><p>Enter a salary and the increase you decide to consider. This calculation is not a recommendation and is not saved.</p><label>Current monthly salary<input type="number" id="salary-current" min="0" step="0.01" oninput="calculateSalaryPlan()"></label><label>Proposed increase (%)<input type="number" id="salary-increase" min="0" step="0.1" oninput="calculateSalaryPlan()"></label><output id="salary-result">Enter both values to compare costs.</output></div>';
 document.getElementById('ov-staff-evidence').classList.add('open');
}
function exportStaffPerformance(){if(!isM()||!hasSectionAccess('workload'))return;const f=performanceFilters(),money=hasSectionAccess('fees');const rows=[['Staff','Period start','Period end','Active clients','Current open tax','Current open accounting','Current open tasks','Overdue tax','Overdue tasks','Blocked on documents','Tax filings in period','Accounting completed in period','Tasks completed in period','On-time tasks numerator','On-time tasks denominator','Completed reports shared','Completed accounting denominator','Older completions without date',...(money?['Currency','Billed','Paid on period invoices','Outstanding on period invoices','Draft amount']:[])],...performanceRows().map(r=>[r.staff.name,f.start,f.end,r.clients,r.tax.length,r.openAccounts.length,r.openTasks.length,r.overdueTax,r.overdueTasks,r.blocked,r.filed.length,r.completedAccounts.length,r.completedTasks.length,r.onTime.length,r.timed.length,r.completedAccounts.filter(e=>e.reportShared).length,r.completedAccounts.length,r.undatedDone,...(money?[f.currency,r.billed,r.paid,r.outstanding,r.draft]:[])])];const quote=v=>'"'+String(v??'').replace(/^[\s]*[=+@\-]/,"'$&").replace(/"/g,'""')+'"';const blob=new Blob(['\uFEFF'+rows.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='staff-performance-'+expiryToday()+'.csv';link.click();URL.revokeObjectURL(url);}
// Preserve tracking through existing whole-record save handlers.
function trackStaffTransition(previous,next,kind){const data={...previous,...next},p={...(previous?.performance||{})},now=new Date().toISOString(),done=kind==='accounting'?'done':'completed';if(previous?.status!==done&&data.status===done){p.completedAt=now;p.completionAdvisorId=data.advisorId||'';if(kind==='tasks')p.completionDue=data.due||'';}if(previous?.status===done&&data.status!==done){delete p.completedAt;delete p.completionAdvisorId;delete p.completionDue;}if(kind==='accounting'&&previous?.status!=='review'&&data.status==='review'){p.reviewSubmissions=(p.reviewSubmissions||0)+1;p.submittedAt=now;}if(kind==='accounting'&&previous?.status==='review'&&data.status==='inprogress'&&data.completionMode!=='direct'){p.reworkCount=(p.reworkCount||0)+1;}if(kind==='accounting'&&previous?.status==='review'&&data.status==='done'&&data.completionMode!=='direct'){p.reviewedAt=now;p.reviewedBy=CU?.name||'';}data.performance=p;return data;}
for(const [name,kind,records] of [['_acctg','accounting',()=>acctEntries],['_tasks','tasks',()=>tasksData]]){const api=window[name],save=api.save,push=api.push;api.save=function(id,data){return save(id,trackStaffTransition(records().find(e=>e.id===id),data,kind));};api.push=function(data){return push(trackStaffTransition(null,data,kind));};}
// Accounting updates otherwise refresh only accounting and reviews.
const performanceAccountingBase=renderAccounting;renderAccounting=function(){performanceAccountingBase();if(CU&&curView==='workload')renderWorkload();};
const performanceFeesBase=renderFees;renderFees=function(){performanceFeesBase();if(CU&&curView==='workload')renderWorkload();};
setTimeout(()=>{const r=performanceRange('month');document.getElementById('perf-start').value=r.start;document.getElementById('perf-end').value=r.end;},0);

function calculateSalaryPlan(){if(!isM())return;const c=document.getElementById('salary-current').value,p=document.getElementById('salary-increase').value;const amount=Number(c),percent=Number(p),result=document.getElementById('salary-result');if(c===''||p===''||!Number.isFinite(amount)||!Number.isFinite(percent)||amount<0||percent<0){result.textContent='Enter valid salary and increase values.';return;}const increase=amount*percent/100;result.textContent='New monthly salary: AED '+performanceMoney(amount+increase)+' · Monthly increase: AED '+performanceMoney(increase)+' · Annual increase: AED '+performanceMoney(increase*12);}
const staffFilingInProgress=new Set(),staffEntrySave=window._entries.save;
window._entries.save=function(id,data){const old=entries.find(e=>e.id===id),performance={...(old?.performance||{})};if(staffFilingInProgress.has(id)){performance.filings={...(performance.filings||{}),[crypto.randomUUID()]:{filedAt:new Date().toISOString(),advisorId:old?.advisorId||'',deadline:old?.deadline||'',recordedBy:CU?.name||''}};}return staffEntrySave(id,{...old,...data,performance});};
const staffMarkFiled=markFiled;markFiled=async function(id){if(!canChangeSection('entries')||staffFilingInProgress.has(id))return;staffFilingInProgress.add(id);try{return await staffMarkFiled(id);}finally{staffFilingInProgress.delete(id);}};
